# Generated by Django 5.1 on 2024-08-24 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_usermodel_role_alter_taskmodel_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskmodel",
            name="assigned_to",
            field=models.ManyToManyField(
                related_name="tasks", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="labels",
            field=models.ManyToManyField(related_name="tasks", to="api.labelmodel"),
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="taskmodel",
            name="sprint",
        ),
        migrations.AlterField(
            model_name="taskmodel",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.statusmodel",
            ),
        ),
        migrations.AddField(
            model_name="taskmodel",
            name="sprint",
            field=models.ManyToManyField(related_name="tasks", to="api.sprintmodel"),
        ),
    ]
